name: build

on: [push, pull_request]

env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'
  MUNIT_FLAKY_OK: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: [adoptium@8, adoptium@17]
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run compile
        run: sbt -v -J-Xmx6g -J-Xss4m headerCheck +compile +test +doc
