name: build

on: [push, pull_request]

env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adoptium@17
      - name: Run compile
        run: sbt headerCheck +compile +test +doc
